// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaZF8iCy9MedqnsdutALoqmuHdALR6jUc',
    appId: '1:808043827714:android:f378bc02b08858ba514d1b',
    messagingSenderId: '808043827714',
    projectId: 'fir-auth-classic',
    storageBucket: 'fir-auth-classic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbMjssEXVbSHwAChfJ6OVoPCzAGO3KzWI',
    appId: '1:808043827714:ios:d441e83ea50d6fe8514d1b',
    messagingSenderId: '808043827714',
    projectId: 'fir-auth-classic',
    storageBucket: 'fir-auth-classic.appspot.com',
    iosClientId: '808043827714-kdfrjiac2m6ig1hfi9fr1ka73vhrfte2.apps.googleusercontent.com',
    iosBundleId: 'agency.q.firebase.auth.classic',
  );
}
